Fatal Python error: Segmentation fault

Current thread 0x0000000113329000 (most recent call first):
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/gl/base.py", line 358 in delete_texture
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/image/__init__.py", line 1439 in __del__
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 407 in get_selector
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 491 in send_super
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1176 in initWithObject_
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 474 in send_message
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 952 in __new__
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 758 in __call__
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 785 in __call__
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/app/cocoa.py", line 183 in notify
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/app/base.py", line 59 in post_event
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/media/__init__.py", line 380 in _sync_dispatch_to_player
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/media/drivers/openal/__init__.py", line 433 in _update_play_cursor
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/media/drivers/openal/__init__.py", line 437 in get_write_size
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/media/drivers/openal/__init__.py", line 112 in run
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/media/__init__.py", line 145 in _thread_run
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/threading.py", line 763 in run
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007fff77d2a310 (most recent call first):
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/image/__init__.py", line 994 in blit_to_texture
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/image/__init__.py", line 811 in create_texture
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/image/__init__.py", line 819 in get_texture
  File "/Users/alexanderschiller/miniconda/envs/text/lib/python2.7/site-packages/pyglet/sprite.py", line 239 in __init__
  File "/Users/alexanderschiller/personal/acceptable_loss/effect.py", line 16 in __init__
  File "/Users/alexanderschiller/personal/acceptable_loss/effect.py", line 55 in bullet_wound
  File "/Users/alexanderschiller/personal/acceptable_loss/character.py", line 86 in on_hit
  File "/Users/alexanderschiller/personal/acceptable_loss/baseskills.py", line 113 in unpack
  File "/Users/alexanderschiller/personal/acceptable_loss/ability.py", line 111 in update
  File "/Users/alexanderschiller/personal/acceptable_loss/character.py", line 99 in update
  File "/Users/alexanderschiller/personal/acceptable_loss/utility.py", line 56 in update
  File "/Users/alexanderschiller/personal/acceptable_loss/states.py", line 317 in update
  File "main.py", line 73 in render
  File "main.py", line 125 in run
  File "main.py", line 135 in <module>
[1]    94287 segmentation fault  python main.py